name: Deploy Docker EBS plugin

on: 
  workflow_dispatch:

jobs: 
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push plugin
        run: |
          pwd
          ls
          go build -o rexray -x
          cp ./rexray .docker/plugins/ebs/
          cd .docker/plugins/ebs/
          docker build -t rootfsimage -f .Dockerfile .
          id=$(docker create rootfsimage true)
          mkdir -p rootfs
          docker export "$id" | sudo tar -x -C rootfs
          docker rm -vf "$id"
          docker rmi rootfsimage
          docker plugin create gendigbadig/rexray-ebs-arm .
          docker plugin push gendigbadig/rexray-ebs-arm
          # DRIVER=ebs make
          # DRIVER=ebs make DOCKER_PLUGIN_NAME=gendigbadig/rexray-ebs build-docker-plugin
          # docker plugin push gendigbadig/rexray-ebs